Feature: setup project
ditrit/leto-modelizer-api pull request #1
Opened 2023-07-28 12:56 UTC by Zorin95670

2023-07-31 14:47 UTC, k-y0u commented on package.json
> +  "description": "Backend for leto-modelizer to manage libraries and access rights management.",
remove `management`

2023-07-31 14:49 UTC, k-y0u commented on src/index.js
> +import { loadConfiguration } from './services/ConfigurationService.js';
`src/services/ConfigurationService.js`

2023-07-31 14:54 UTC, k-y0u commented on src/index.js
> +  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
what is this message ? XD

2023-07-31 14:55 UTC, k-y0u commented on src/models/Configuration.js
> + * All api configuration key and value.
keys and values

2023-07-31 14:59 UTC, k-y0u commented on tests/unit/models/Configuration.spec.js
> +    it('Checks variable instantiation', () => {
variables

2023-07-31 15:36 UTC, justinehell requested changes

2023-07-31 15:36 UTC, justinehell commented on .eslintrc.cjs
> +    "plugin:cypress/recommended"
why double quote instead of single one ?

2023-07-31 15:36 UTC, justinehell commented on src/models/Configuration.js
> +   * for incoming connections from clients.
```suggestion
   * for incoming client connections.
```

2023-07-31 15:36 UTC, justinehell commented on src/models/Configuration.js
> +   * @param {string} [props.mountPath] - That specifies the mount path where the Parse middleware
Missing .

2023-07-31 15:36 UTC, justinehell commented on src/models/Configuration.js
> +   * used to distinguish it when interacting with the Parse backend
missing .

2023-07-31 15:36 UTC, justinehell commented on src/models/Configuration.js
> +     * administrative-level operations and data management
Missing .

2023-07-31 15:36 UTC, justinehell commented on CONTRIBUTING.md
> +Release tag are only done on the `main` branch.
Release tags are ...

2023-08-01 08:27 UTC, justinehell requested changes

2023-08-01 08:27 UTC, justinehell commented on README.md
> +SERVER_URL=http://localhost:1337/api
Maybe add here at least **all the required** variables
At first, I thought these three were enough.

2023-08-01 08:27 UTC, justinehell commented on README.md
> +    * [Docker Engine for Linux]()
add links

2023-08-01 08:27 UTC, justinehell commented on README.md
> +SERVER_URL (http://localhost:1337/api in this example).
![image](https://github.com/ditrit/leto-modelizer-api/assets/62500081/8ed5b1ca-c615-4e2b-a7f7-8cab63974d59)

2023-08-01 08:37 UTC, Zorin95670 commented on package.json
> +  "description": "Backend for leto-modelizer to manage libraries and access rights management.",
done

2023-08-01 08:37 UTC, Zorin95670 commented on src/index.js
> +import { loadConfiguration } from './services/ConfigurationService.js';
Nope

2023-08-01 08:37 UTC, k-y0u commented on README.md
> +2. Clone the repository: Open your terminal or command prompt and clone the project repository to your local machine:
to your machine

2023-08-01 08:52 UTC, k-y0u commented on README.md
> +SERVER_URL=http://localhost:1337/api
`NODE_ENV` missing but indicate as required below.

2023-08-01 08:53 UTC, Zorin95670 commented on src/index.js
> +const httpServer = http.createServer(app);
done

2023-08-01 08:53 UTC, k-y0u commented on README.md
> +3. Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
Couldn't it be `dev.env`, `staging.env` or else ?

2023-08-01 08:53 UTC, Zorin95670 commented on src/index.js
> +  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
done

2023-08-01 08:54 UTC, Zorin95670 commented on src/models/Configuration.js
> + * All api configuration key and value.
done

2023-08-01 08:54 UTC, Zorin95670 commented on tests/unit/models/Configuration.spec.js
> +    it('Checks variable instantiation', () => {
done

2023-08-01 08:54 UTC, Zorin95670 commented on README.md
> +Backend for leto-modelizer to manage libraries and access rights management.
done

2023-08-01 08:55 UTC, Zorin95670 commented on .eslintrc.cjs
> +    "plugin:cypress/recommended"
done

2023-08-01 08:55 UTC, Zorin95670 commented on src/models/Configuration.js
> +   * for incoming connections from clients.
done

2023-08-01 08:56 UTC, Zorin95670 commented on src/models/Configuration.js
> +   * @param {string} [props.mountPath] - That specifies the mount path where the Parse middleware
done

2023-08-01 08:57 UTC, Zorin95670 commented on src/models/Configuration.js
> +     * administrative-level operations and data management
done

2023-08-01 08:57 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Release tag are only done on the `main` branch.
done

2023-08-01 08:57 UTC, Zorin95670 commented on CONTRIBUTING.md
> +## Development
done

2023-08-01 08:58 UTC, Zorin95670 commented on README.md
> +git clone git+https://github.com/ditrit/leto-modelizer-api.git
done

2023-08-01 08:59 UTC, Zorin95670 commented on README.md
> +| Variable     | Optional ?                                | Example                                               | Description
done

2023-08-01 08:59 UTC, Zorin95670 commented on README.md
> +Verify Installation: Once the containers are up and running, you can access your servver at the defined
done

2023-08-01 09:00 UTC, k-y0u commented on README.md
> +SERVER_URL=http://localhost:1337/api
`DATABASE_URI` missing but indicate as required below.

2023-08-01 09:02 UTC, Zorin95670 commented on README.md
> +SERVER_URL=http://localhost:1337/api
done

2023-08-01 09:03 UTC, Zorin95670 commented on README.md
> +    * [Docker Engine for Linux]()
done

2023-08-01 09:04 UTC, Zorin95670 commented on README.md
> +SERVER_URL (http://localhost:1337/api in this example).
Normal you must provide authentication :)

2023-08-01 09:04 UTC, Zorin95670 commented on README.md
> +2. Clone the repository: Open your terminal or command prompt and clone the project repository to your local machine:
done

2023-08-01 09:05 UTC, Zorin95670 commented on README.md
> +SERVER_URL=http://localhost:1337/api
Not done, set all variable to make an example

2023-08-01 09:05 UTC, Zorin95670 commented on README.md
> +SERVER_URL=http://localhost:1337/api
done

2023-08-01 09:06 UTC, Zorin95670 commented on README.md
> +3. Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
you could name it as you want, but you have to use same name in `NODE_ENV`, as explain in documentation :)

2023-08-01 09:06 UTC, Zorin95670 commented on README.md
> +SERVER_URL=http://localhost:1337/api
done

2023-08-01 09:58 UTC, k-y0u commented on src/index.js
> +import { loadConfiguration } from './services/ConfigurationService.js';
what's the link ?

2023-08-01 10:02 UTC, justinehell submitted a review, later dismissed

2023-08-01 10:03 UTC, k-y0u commented on README.md
> +Build and Run with Docker Compose: Run the following command to build the Docker containers and start the server:
step one

2023-08-01 10:04 UTC, k-y0u commented on README.md
> +Verify Installation: Once the containers are up and running, you can access your server at the defined
step two

2023-08-01 10:04 UTC, k-y0u commented on README.md
> +Clean Up: To stop and remove the Docker containers when you're done using the project, run:
step three

2023-08-01 10:08 UTC, k-y0u commented on README.md
> +docker build --build-arg -t leto-modelizer-api .
forgot `NODE_ENV=[env_name]`

2023-08-01 10:08 UTC, k-y0u commented on README.md
> +Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
remove `Set up Environment Variables:`

2023-08-01 10:09 UTC, k-y0u commented on README.md
> +Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
`prod.env` -> `[env_name].env`

2023-08-01 12:03 UTC, Zorin95670 commented on README.md
> +Build and Run with Docker Compose: Run the following command to build the Docker containers and start the server:
done

2023-08-01 12:03 UTC, Zorin95670 commented on README.md
> +Verify Installation: Once the containers are up and running, you can access your server at the defined
done

2023-08-01 12:03 UTC, Zorin95670 commented on README.md
> +Clean Up: To stop and remove the Docker containers when you're done using the project, run:
done

2023-08-01 12:03 UTC, Zorin95670 commented on README.md
> +docker build --build-arg -t leto-modelizer-api .
done

2023-08-01 12:04 UTC, Zorin95670 commented on README.md
> +Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
done

2023-08-01 12:04 UTC, Zorin95670 commented on README.md
> +Set up Environment Variables: Create a `prod.env` file in the root of the project directory to store your
done

2023-08-01 12:04 UTC, Zorin95670 commented on README.md
> +NODE_ENV=prod
done

2023-08-01 12:06 UTC, Zorin95670 commented on src/index.js
> +import { loadConfiguration } from './services/ConfigurationService.js';
so we can't use src because it need to be babelize

2023-08-01 12:11 UTC, k-y0u commented on README.md
> +docker build --build-arg -t leto-modelizer-api .
nope

2023-08-01 12:17 UTC, k-y0u approved these changes

2023-08-01 12:19 UTC, justinehell approved these changes

2023-08-01 13:18 UTC, AlexisNeveu approved these changes

2023-08-02 08:28 UTC, Zorin95670 commented on jest.config.cjs
> +  // transform: {
done

2023-08-02 08:50 UTC, Zorin95670 commented on src/models/Configuration.js
> +   * @param {number} [props.port] - The network port number on which a server process listens
it's good.

2023-08-02 08:54 UTC, justinehell approved these changes

2023-08-02 09:02 UTC, aboubakar14 approved these changes

2023-08-02 09:03 UTC, merged