Feature/roles management
ditrit/leto-modelizer-api pull request #14
Opened 2023-10-09 21:19 UTC by AlexisNeveu

Role entity definition and tests

2023-10-17 09:31 UTC, Zorin95670 commented on src/services/ConfigurationService.js
> +      entities: [User, Group, Role],
missing default `role:admin` creation on startup of server

2023-10-20 07:53 UTC, Zorin95670 commented on src/init.js
> +export async function upgrade(configuration, Parse = parse) {
setudDefaultRoles(configuration)

2023-10-20 07:53 UTC, Zorin95670 commented on src/init.js
> +async function initAdminRole(Parse) {
initRole(roleName)

2023-10-20 07:53 UTC, Zorin95670 commented on src/init.js
> +async function initParse(configuration, Parse) {
initParse(configuration)

2023-10-20 07:54 UTC, Zorin95670 commented on src/init.js
> +    return adminRole;
return Promise.reject()

2023-10-20 07:55 UTC, Zorin95670 commented on src/init.js
> +    return adminRole;
return Promise.resolve()

2023-10-20 07:57 UTC, Zorin95670 commented on src/init.js
> +import parse from 'parse/node.js';
rework on breakline

2023-10-20 07:59 UTC, Zorin95670 commented on tests/e2e/features/Role.feature
> +  Scenario: Set and unset a Role to a User
Add scenario to verify admin role is created.

2023-10-20 13:02 UTC, AlexisNeveu commented on src/init.js
> +async function initAdminRole(Parse) {
done

2023-10-20 13:03 UTC, AlexisNeveu commented on src/init.js
> +    return adminRole;
done

2023-10-20 13:03 UTC, AlexisNeveu commented on src/init.js
> +    return adminRole;
modified : return Promise.resolve()

2023-10-20 13:04 UTC, AlexisNeveu commented on src/init.js
> +import parse from 'parse/node.js';
done

2023-10-20 13:04 UTC, AlexisNeveu commented on tests/e2e/features/Role.feature
> +  Scenario: Set and unset a Role to a User
done

2023-10-20 13:16 UTC, Zorin95670 commented on src/init.js
> +    return Promise.resolve();
after reading your new code version, you can remove this line

2023-10-20 13:17 UTC, Zorin95670 commented on src/init.js
> + * Function to be called after the start of the api.
rework on documentation

2023-10-20 13:17 UTC, Zorin95670 commented on src/init.js
> +  await initRole('admin', Parse)
we can only keep `await initRole(...);`

2023-10-20 15:03 UTC, Zorin95670 commented on src/init.js
> +    newRole = await newRole.save({}, { useMasterKey: true });
newRole is never used, remove it.

2023-10-20 15:03 UTC, Zorin95670 commented on src/init.js
> +    return true;
put at the end of function

2023-10-23 07:39 UTC, justinehell requested changes

2023-10-23 07:39 UTC, justinehell commented on src/init.js
> +  // If the role already exists we have nothing to do here
```suggestion
  // If the role already exists, we have nothing to do here
```

2023-10-23 07:39 UTC, justinehell commented on src/init.js
> +  initParse(configuration, Parse);
no need to `await initParse(...)` ?

2023-10-23 07:39 UTC, justinehell commented on tests/unit/init.spec.js
> +  it('should return a resolved promise with false if query fails', async () => {
jump line before

2023-10-23 07:39 UTC, justinehell commented on tests/unit/init.spec.js
> +  it('should resolved promise with false if the save fails', async () => {
jump line before

2023-10-23 07:39 UTC, justinehell commented on tests/unit/init.spec.js
> +  it('should resolved promise with false if the save fails', async () => {
`should return a revolved promise...`

2023-10-23 07:39 UTC, justinehell commented on tests/e2e/support/step_definitions/request.js
> + * @param {boolean} form - Whether to convert the body values to URL encoded content.
weird naming `form` for boolean

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> +    return Promise.resolve();
done

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> + * Function to be called after the start of the api.
done

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> +  await initRole('admin', Parse)
done

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> +    return true;
done

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> + */
done

2023-10-23 08:47 UTC, AlexisNeveu commented on src/init.js
> + * Setup every default default roles needed at the initialization of the server.
done

2023-10-23 08:48 UTC, AlexisNeveu commented on src/init.js
> +  // If the role already exists we have nothing to do here
done

2023-10-23 08:48 UTC, AlexisNeveu commented on tests/unit/init.spec.js
> +  it('should return a resolved promise with false if query fails', async () => {
done

2023-10-23 08:48 UTC, AlexisNeveu commented on tests/unit/init.spec.js
> +  it('should resolved promise with false if the save fails', async () => {
done

2023-10-23 08:48 UTC, AlexisNeveu commented on tests/unit/init.spec.js
> +  it('should resolved promise with false if the save fails', async () => {
done

2023-10-23 08:48 UTC, AlexisNeveu commented on tests/e2e/support/step_definitions/request.js
> + * @param {boolean} form - Whether to convert the body values to URL encoded content.
done

2023-10-23 08:58 UTC, Zorin95670 commented on src/init.js
> + * @param {*} Parse - The Parse object to use SDK functionalities.
Missing return

2023-10-23 09:08 UTC, AlexisNeveu commented on src/init.js
> + * @param {*} Parse - The Parse object to use SDK functionalities.
done

2023-10-23 09:28 UTC, Zorin95670 approved these changes

2023-10-23 09:28 UTC, justinehell approved these changes

2023-10-23 09:40 UTC, merged