Bugfix/enable master key for selected ips
ditrit/leto-modelizer-api pull request #2
Opened 2023-08-11 12:04 UTC by AlexisNeveu

2023-08-11 13:25 UTC, Zorin95670 requested changes

2023-08-11 13:25 UTC, Zorin95670 commented on src/models/Configuration.js
> +   * @param {Array.<string>} [props.parseServer.masterKeyIps] - Restrict masterKey to be used
- string[]
- Missing `.`
- `Restricted ip that can use masterKey.`

2023-08-11 13:25 UTC, Zorin95670 commented on src/models/Configuration.js
> +     * @type {Array.<string>}
missing default

2023-08-11 13:25 UTC, Zorin95670 commented on src/services/ConfigurationService.js
> +      masterKeyIps: process.env.MASTER_KEY_IPS?.split(' ') || ['0.0.0.0/0'],
`process.env.MASTER_KEY_IPS?.split(','),`

2023-08-11 13:25 UTC, Zorin95670 commented on README.md
> +| MASTER_KEY_IPS | No, default: 0.0.0.0/0               | 0.0.0.0/0                                             | Restrict masterKey to be used by only these ips. 0.0.0.0/0 enables any ip |
Bad indentation

2023-08-11 13:25 UTC, Zorin95670 commented on README.md
> +MASTER_KEY_IPS=1.1.1.1/1 2.2.2.2/2 3.3.3.3/3
add `,` instead of ` `

2023-08-16 12:07 UTC, aboubakar14 commented on README.md
> +| MASTER_KEY_IPS | No, default: [], no ip allowed           | 0.0.0.0/0                                             | Restrict masterKey to be used by only these ips. 0.0.0.0/0 enables any ip, not re
Missing dot at the end of the sentence in the description

2023-08-17 12:54 UTC, aboubakar14 approved these changes

2023-08-17 12:54 UTC, Zorin95670 approved these changes

2023-08-17 12:54 UTC, merged