Feature/simple authentication
ditrit/leto-modelizer-api pull request #3
Opened 2023-08-21 09:28 UTC by AlexisNeveu

User class setup in parse and e2e tests for authentication

2023-09-05 09:37 UTC, Zorin95670 requested changes

2023-09-05 09:37 UTC, Zorin95670 commented on package.json
> -  "name": "leto-modelizer-api",
Remove package-lock.json and package.json mpdification from commit Update configuration

2023-09-05 09:37 UTC, Zorin95670 commented on package.json
> +  }
Missing end line

2023-09-05 09:37 UTC, Zorin95670 commented on src/services/ConfigurationService.js
> +      schema: {
move this to configuration

2023-09-05 09:37 UTC, Zorin95670 commented on tests/e2e/support/step_definitions/request.js
> +});
Missing end of line

2023-09-05 09:37 UTC, Zorin95670 commented on src/entities/user.js
> +/**
user.js -> User.js

2023-09-05 09:37 UTC, Zorin95670 commented on tests/unit/services/ConfigurationService.spec.js
> +import User from '../../../src/entities/user';
change by `src/entities/User`, may be you have to update babel or jest configuration to be able to do that.

2023-09-05 09:37 UTC, Zorin95670 commented on src/models/Configuration.js
> +      schema: {},
change by: entities: [],
and after :
```js
this.parseServer.schema = {
        definitions: props.entities || [],
        // If set to `true`, the Parse Server API for schema changes is disabled and schema
        // changes are only possible by redeployingParse Server with a new schema definition
        lockSchemas: true,
        // If set to `true`, Parse Server will automatically delete non-defined classes from
        // the database; internal classes like `User` or `Role` are never deleted.
        strict: true,
        // If set to `true`, a field type change will cause the field including its data to be
        // deleted from the database, and then a new field to be created with the new type
        recreateModifiedFields: false,
        // If set to `true`, Parse Server will automatically delete non-defined class fields;
        // internal fields in classes like User or Role are never deleted.
        deleteExtraFields: false,
};
```

2023-09-05 09:37 UTC, Zorin95670 commented on changelog.md
> +### Added
already exists section

2023-09-06 08:29 UTC, Zorin95670 submitted a review, later dismissed

2023-09-06 09:30 UTC, k-y0u requested changes

2023-09-06 09:30 UTC, k-y0u commented on changelog.md
> +* User entity definition.
update changelog should be your last commit.

2023-09-06 09:30 UTC, k-y0u commented on src/services/ConfigurationService.js
> +import User from '../entities/User.js';
not existing yet. reorder commit.

2023-09-06 09:55 UTC, k-y0u commented on src/models/Configuration.js
> +   * @param {object} [props.parseServer.entities] - Define the list of entities in the database.
My bad, it was `Array`

2023-09-06 10:28 UTC, aboubakar14 commented on src/models/Configuration.js
> +      // If set to `true`, the Parse Server API for schema changes is disabled and schema
I would say: "If set to `true`, schema changes are disabled and appliying them is only possible ..."

2023-09-06 10:28 UTC, aboubakar14 commented on tests/e2e/support/step_definitions/request.js
> +  const headers = {
Maybe there is a way to automatically add headers in all steps in one time ? Instead of adding header in each step definition

2023-09-06 10:28 UTC, aboubakar14 commented on package.json
> +    "cypress": "=13.1.0",
I think this one is not working on the CI, to check with @Zorin95670

2023-09-06 13:42 UTC, Zorin95670 commented on package.json
> +    "cypress": "=13.1.0",
CI is green so it's ok :)

2023-09-06 13:46 UTC, justinehell approved these changes

2023-09-06 14:40 UTC, aboubakar14 approved these changes

2023-09-06 14:53 UTC, k-y0u approved these changes

2023-09-06 14:59 UTC, Zorin95670 approved these changes

2023-09-06 15:01 UTC, DimitriChauvel approved these changes

2023-09-06 15:02 UTC, merged