Feature/add whitelist for library
ditrit/leto-modelizer-api pull request #30
Opened 2023-12-14 14:31 UTC by AlexisNeveu

Add a whitelist for the url domain trusted when importing a new library

2023-12-15 08:53 UTC, Zorin95670 commented on src/models/Configuration.js
> +      domainWhitelist: null,
default: []

2023-12-15 08:54 UTC, Zorin95670 commented on src/models/Configuration.js
> +    this.parseServer.domainWhitelist = props.parseServer?.domainWhitelist?.split(',') || ['http://templates'];
remove 'http://templates', user must defined it.

2023-12-15 08:58 UTC, Zorin95670 commented on src/cloud/library.js
> +  if (!configuration.parseServer.domainWhitelist.includes(`${protocol}://${domain}`)) {
Change by:
```js
if (!configuration.parseServer.domainWhiteListe.some((accepted) => url.startsWith(accepted))) {
  throw ...;
}
````

2023-12-15 09:00 UTC, Zorin95670 commented on dev.env
> +DOMAIN_WHITELIST=http://templates,https://raw.githhubusercontent.com
http://templates/,https://raw.githubusercontent.com/ditrit/

2023-12-15 09:01 UTC, Zorin95670 commented on README.md
> +| DOMAIN_WHITELIST                | No, default: `http://templates`                             | `http://templates,https://mytrusteddomain`            | List the domain trusted from where it is poss
No, default: `http://templates`  -> Yes
`http://templates/,https://mytrusteddomain`/

2023-12-15 09:02 UTC, Zorin95670 commented on tests/e2e/features/Library.feature
> +      | url      | https://raw.githubusercontent.com/ditrit/leto-modelizer-templates-library/main/index.json |
should be accepted because its url is in the dev.env ?

2023-12-15 11:23 UTC, AlexisNeveu commented on tests/e2e/features/Library.feature
> +      | url      | https://raw.githubusercontent.com/ditrit/leto-modelizer-templates-library/main/index.json |
Yes, just a typo in dev.env

2023-12-19 15:27 UTC, AlexisNeveu commented on src/models/Configuration.js
> +      domainWhitelist: null,
done

2023-12-19 15:27 UTC, AlexisNeveu commented on src/models/Configuration.js
> +    this.parseServer.domainWhitelist = props.parseServer?.domainWhitelist?.split(',') || ['http://templates'];
done

2023-12-19 15:27 UTC, AlexisNeveu commented on src/cloud/library.js
> +  if (!configuration.parseServer.domainWhitelist.includes(`${protocol}://${domain}`)) {
done

2023-12-19 15:27 UTC, AlexisNeveu commented on dev.env
> +DOMAIN_WHITELIST=http://templates,https://raw.githhubusercontent.com
done

2023-12-19 15:27 UTC, AlexisNeveu commented on README.md
> +| DOMAIN_WHITELIST                | No, default: `http://templates`                             | `http://templates,https://mytrusteddomain`            | List the domain trusted from where it is poss
done

2023-12-19 15:28 UTC, AlexisNeveu commented on tests/e2e/features/Library.feature
> +      | url      | https://raw.githubusercontent.com/ditrit/leto-modelizer-templates-library/main/index.json |
done

2023-12-21 13:11 UTC, Zorin95670 commented on dev.env
> +DOMAIN_WHITELIST=http://templates,https://raw.githhubusercontent.com
Not done, its important to keep the `/` at the end, because if we don't we can specify another like
http://templates/,https://raw.githubusercontent.com/ditrit-fake and it will be ok.

2023-12-21 13:12 UTC, Zorin95670 commented on README.md
> +| DOMAIN_WHITELIST                | No, default: `http://templates`                             | `http://templates,https://mytrusteddomain`            | List the domain trusted from where it is poss
no, still missing `/` at the end

2023-12-21 13:43 UTC, Zorin95670 commented on README.md
> +DOMAIN_WHITELIST=http://templates,https://mytrusteddomain/
http://templates/

2023-12-21 14:04 UTC, Zorin95670 requested changes

2023-12-21 14:04 UTC, Zorin95670 commented on src/models/Configuration.js
> +   * @param {string} [props.parseServer.domainWhitelist] - Define the domains authorized to
authorized domains

2023-12-21 14:04 UTC, Zorin95670 commented on src/models/Configuration.js
> +     * Define the domains authorized to import new libraries.
same

2023-12-21 14:04 UTC, Zorin95670 commented on tests/unit/models/Configuration.spec.js
> +          domainWhitelist: 'http://templates,https://templates',
`/`

2023-12-21 14:04 UTC, Zorin95670 commented on tests/unit/models/Configuration.spec.js
> +      expect(configuration.parseServer.domainWhitelist).toEqual(['http://templates', 'https://templates']);
`/`

2023-12-21 14:04 UTC, Zorin95670 commented on tests/unit/cloud/library.spec.js
> -describe('Test function: fillLibraryFields', () => {
prefer to have a special commit for this deletion

2023-12-21 14:04 UTC, Zorin95670 commented on dev.env
> +DOMAIN_WHITELIST=http://templates/lib1/,http://templates/lib2,https://raw.githubusercontent.com/ditrit/
`/`

2023-12-21 14:04 UTC, Zorin95670 commented on tests/e2e/features/Library.feature
> +      | roleName | mylibrole                                     |
bad indentation

2023-12-21 14:04 UTC, Zorin95670 commented on README.md
> +| DOMAIN_WHITELIST                | Yes                                                         | `http://templates/,https://mytrusteddomain/           | List the domain trusted from where it is poss
the trusted domain

2023-12-21 14:04 UTC, Zorin95670 commented on changelog.md
> +* Domain whitelist as an env variable in order to accept libraries from only specified domains.
Add whitelist for domain, to list all accepted domain for library importation.

2023-12-22 13:51 UTC, AlexisNeveu commented on src/models/Configuration.js
> +   * @param {string} [props.parseServer.domainWhitelist] - Define the domains authorized to
done

2023-12-22 13:51 UTC, AlexisNeveu commented on src/models/Configuration.js
> +     * Define the domains authorized to import new libraries.
done

2023-12-22 13:56 UTC, AlexisNeveu commented on tests/unit/models/Configuration.spec.js
> +          domainWhitelist: 'http://templates,https://templates',
done

2023-12-22 13:56 UTC, AlexisNeveu commented on tests/unit/models/Configuration.spec.js
> +      expect(configuration.parseServer.domainWhitelist).toEqual(['http://templates', 'https://templates']);
done

2023-12-22 13:56 UTC, AlexisNeveu commented on tests/unit/cloud/library.spec.js
> -describe('Test function: fillLibraryFields', () => {
done

2023-12-22 13:57 UTC, AlexisNeveu commented on dev.env
> +DOMAIN_WHITELIST=http://templates/lib1/,http://templates/lib2,https://raw.githubusercontent.com/ditrit/
done

2023-12-22 13:58 UTC, AlexisNeveu commented on tests/e2e/features/Library.feature
> +      | roleName | mylibrole                                     |
done

2023-12-22 13:59 UTC, AlexisNeveu commented on README.md
> +| DOMAIN_WHITELIST                | Yes                                                         | `http://templates/,https://mytrusteddomain/           | List the domain trusted from where it is poss
done

2023-12-22 14:08 UTC, AlexisNeveu commented on changelog.md
> +* Domain whitelist as an env variable in order to accept libraries from only specified domains.
Done

2023-12-22 14:27 UTC, Zorin95670 approved these changes

2023-12-22 14:27 UTC, merged