Feature: setup java api
ditrit/leto-modelizer-api pull request #31
Opened 2024-01-08 16:17 UTC by Zorin95670

2024-01-09 15:58 UTC, justinehell requested changes

2024-01-09 15:58 UTC, justinehell commented on CONTRIBUTING.md
> +you can run:
One sentence like :
Once database is setup and the dev.env file is filled (cf: README.md), you can run :

2024-01-09 15:58 UTC, justinehell commented on CONTRIBUTING.md
> +> :warning: **You have to generate keystore.jks before!**
maybe add link to the corresponding paragraph in README.md ?

2024-01-09 15:58 UTC, justinehell commented on CONTRIBUTING.md
> +Before, push you branch and open/synchronize a pull-request. You have to verify the checkstyle of your application, here is the command:
Before pushing your branch and open/synchronize a pull-request, you have to verify the checkstyle of your application. Here is the command to do so:

2024-01-09 15:58 UTC, justinehell commented on CONTRIBUTING.md
> +Reports can be find in:
Reports can be found in:

2024-01-09 15:58 UTC, justinehell commented on README.md
> +| SSL_KEY_STORE           | No, default: `classpath:keystore.jks`  | a configuration parameter specifying the file path to the keystore containing SSL/TLS certificates and keys for secure connections
a configuration -> A configuration...

2024-01-09 15:58 UTC, justinehell commented on README.md
> +Then run your docker compose.
Then run your docker compose with this command:

2024-01-09 16:01 UTC, Zorin95670 commented on src/main/resources/application.properties
> +server.ssl.key-password=${SSL_KEY_PASSWORD:password}
done

2024-01-09 16:01 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Before, push you branch and open/synchronize a pull-request. You have to verify the checkstyle of your application, here is the command:
done

2024-01-09 16:02 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Reports can be find in:
done

2024-01-09 16:02 UTC, Zorin95670 commented on CONTRIBUTING.md
> +You can check dependencies of your code, by running this command:
done

2024-01-09 16:03 UTC, Zorin95670 commented on CONTRIBUTING.md
> +You can check dependencies of your code, by running this command:
done

2024-01-09 16:03 UTC, Zorin95670 commented on CONTRIBUTING.md
> +Reports can be find in:
done

2024-01-09 16:03 UTC, Zorin95670 commented on CONTRIBUTING.md
>  The default branch is main. Direct commit on it is forbidden. The only way to update the application is through pull request.
done

2024-01-09 16:04 UTC, Zorin95670 commented on README.md
> +- `admin`: allow user to access and use `leto-modelizer-admin`.
done

2024-01-09 16:04 UTC, Zorin95670 commented on README.md
> +Then run your docker compose.
done

2024-01-09 16:18 UTC, Zorin95670 commented on CONTRIBUTING.md
> +> :warning: **You have to generate keystore.jks before!**
done

2024-01-10 09:20 UTC, justinehell approved these changes

2024-01-10 09:21 UTC, merged