Feature: role endpoints
ditrit/leto-modelizer-api pull request #38
Opened 2024-01-25 14:33 UTC by Zorin95670

2024-01-29 16:41 UTC, justinehell requested changes

2024-01-29 16:41 UTC, justinehell commented on src/test/resources/features/Role.feature
> +    And I expect response field "cause" is "NOT_NULL"
missing end line

2024-01-29 16:42 UTC, justinehell commented on src/main/java/com/ditrit/letomodelizerapi/model/accesscontrol/AccessControlType.java
> + *         Roles are typically used to group sets of permissions and can be assigned to users or groups to grant those
if you mean at the end of sentence, I can see them

2024-01-30 09:43 UTC, Zorin95670 commented on src/test/java/com/ditrit/letomodelizerapi/cucumber/StepDefinitions.java
> +        System.out.println();
done

2024-01-30 09:43 UTC, Zorin95670 commented on src/test/java/com/ditrit/letomodelizerapi/cucumber/StepDefinitions.java
> +    @Given("I init admin")
done

2024-01-30 09:44 UTC, Zorin95670 commented on src/test/resources/features/Role.feature
> +    And I expect response field "cause" is "NOT_NULL"
done

2024-01-30 09:44 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +        userPermissionService.checkIsAdmin(user, null);
in another pr, not the purpose of this request. Should be comment in previous pr when I work on the acl...

2024-01-30 09:55 UTC, justinehell approved these changes

2024-01-30 09:57 UTC, merged