Feature: link users and roles
ditrit/leto-modelizer-api pull request #39
Opened 2024-01-31 10:32 UTC by Zorin95670

2024-01-31 13:27 UTC, justinehell requested changes
`usa_id`
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDhtOHV5cndheWhhYTkwbDZ1OTd1ZDJweGpsd2h1dHM0aTB6NXhuZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RfSTDk1BewjP8sfr2O/giphy.gif)

2024-01-31 13:27 UTC, justinehell commented on src/test/java/com/ditrit/letomodelizerapi/service/AccessControlServiceImplTest.java
> +    @DisplayName("Test associate: should throw exception on already exists association")
`should throw exception on already existing association`

2024-01-31 13:27 UTC, justinehell commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +     * @param id      the ID of the role with which the user is to be associated.
the ID of the role to which the user is to be associated.

2024-01-31 13:27 UTC, justinehell commented on src/test/resources/features/Role.feature
> +  Scenario: Should return all user associate to specific role
Should return all users associated with a specific role

2024-01-31 14:12 UTC, AboubakarKhan14 commented on src/main/java/com/ditrit/letomodelizerapi/controller/CurrentUserController.java
> +     * Retrieves all roles associated with the current user.
to the current user

2024-02-01 09:33 UTC, Zorin95670 commented on src/test/java/com/ditrit/letomodelizerapi/service/AccessControlServiceImplTest.java
> +    @DisplayName("Test associate: should throw exception on already exists association")
done

2024-02-01 09:34 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +     * @param id      the ID of the role with which the user is to be associated.
done

2024-02-01 09:35 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/persistence/model/UserAccessControlView.java
> + * Represents a user access control entity in the system.
If it's not an entity what is it ?

2024-02-01 09:37 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +    public Response getUsersOfRole(final @Context HttpServletRequest request,
done

2024-02-01 09:37 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +     * Associates a user with a specified role.
done

2024-02-01 09:37 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/RoleController.java
> +     * Retrieves users associated with a specific role.
done

2024-02-01 09:39 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/CurrentUserController.java
> +     * Retrieves all roles associated with the current user.
done

2024-02-01 09:49 UTC, justinehell approved these changes

2024-02-01 09:55 UTC, merged