Feature: get endpoint for libraries and templates
ditrit/leto-modelizer-api pull request #49
Opened 2024-02-19 14:48 UTC by Zorin95670

2024-02-19 16:00 UTC, justinehell requested changes

2024-02-19 16:00 UTC, justinehell commented on src/main/java/com/ditrit/letomodelizerapi/controller/LibraryController.java
> +     * the icon data and headers. The actual implementation of getIcon may vary.
Is this note supposed to be here ? I find it weird (we should be aware of how `getIcon` is implemented)
Same comment for the other `Note:` like this in this PR

2024-02-20 07:55 UTC, Zorin95670 commented on src/main/java/com/ditrit/letomodelizerapi/controller/LibraryController.java
> +     * the icon data and headers. The actual implementation of getIcon may vary.
done

2024-02-20 08:56 UTC, justinehell approved these changes

2024-02-20 08:57 UTC, merged