Feature/users group
ditrit/leto-modelizer-api pull request #6
Opened 2023-09-07 14:13 UTC by AlexisNeveu

Creation of the users group entity with e2e tests

2023-09-08 07:51 UTC, Zorin95670 commented on src/entities/Group.js
> + * Definition of the Group entity
Add explanation of groups and sub attribute.

2023-09-08 07:52 UTC, Zorin95670 commented on tests/e2e/features/Group.feature
> +    And I expect body field "objectId" is "{{user_id}}"
this line is useless, delete all line like this

2023-09-08 07:54 UTC, Zorin95670 commented on tests/e2e/support/step_definitions/request.js
> +When('I request {string} with method {string} with masterKey and json', (endpointTemplate, method, operator) => {
operator -> body

2023-09-08 07:58 UTC, Zorin95670 requested changes

2023-09-08 07:58 UTC, Zorin95670 commented on tests/e2e/features/Group.feature
> +    "users" : { "__op": "AddRelation", "objects": [ {"__type": "Pointer", "className": "_User", "objectId": "{{user_id}}"} ] }
why don't you have `{ "users": ...}` ?
And reorganise json properly  like:
```
"users":  {
  "op": ...,
  "objets": [
    ...
   ]
}
```

2023-09-21 08:03 UTC, justinehell requested changes

2023-09-21 08:03 UTC, justinehell commented on tests/unit/cloud/cloud-functions.spec.js
> +    await group.save({}, { useMasterKey: true });
jump line before

2023-09-21 08:42 UTC, aboubakar14 commented on src/cloud/cloud-functions.js
> +/**
Missing description

2023-09-21 08:42 UTC, aboubakar14 commented on src/cloud/main.js
> +/* eslint-disable */
why are you disabling eslint ?

2023-09-21 08:42 UTC, aboubakar14 commented on src/cloud/cloud-functions.js
> +export async function isGroupUnique(isExistingObject, objectName, sessionToken, Parse) {
I am not sure that I understand properly the purpose of ̀ `isExistingObject`, if we can know if the object exist, why would we call this function ?
For instance, in my opinion I would rather do in cloud/main.js:beforeSave():

`if (!isExistingObject) {
    await isGroupUnique(objectName, sessionToken, Parse);
}`

2023-09-21 08:42 UTC, aboubakar14 commented on tests/e2e/features/Group.feature
> +  Scenario: Create a group
To avoid having the same issue as on leto-modelizer, I would merge together these 2 tests.

- Purge -> status code 200
- Creating one group -> status code 201
- Creating the same one -> status code 400

2023-09-21 08:42 UTC, aboubakar14 commented on tests/e2e/support/step_definitions/request.js
> +Then('I set body field {string} to context field {string}', (key, contextField) => {
Not used ?

2023-09-21 08:45 UTC, aboubakar14 commented on src/entities/Group.js
> +const Group = {
maybe unit testing that entity ?
I know it may be not very interesting but later on it could be and also it would be good for Sonar

2023-09-22 08:28 UTC, aboubakar14 commented on src/cloud/cloud-functions.js
> + * This function is called when by the Group entity beforeSave Trigger.
`This function is called by the Group entity beforeSave() Trigger.`

2023-09-22 09:42 UTC, justinehell commented on tests/e2e/features/Group.feature
> +    "users" : { "__op": "AddRelation", "objects": [ {"__type": "Pointer", "className": "_User", "objectId": "{{user_id}}"} ] }
Code deleted, it will be done in the PR related to user management in a group

2023-09-26 14:00 UTC, k-y0u requested changes

2023-09-26 14:11 UTC, AlexisNeveu commented on src/services/ConfigurationService.js
> +      cloud: 'src/cloud/main.js',
done

2023-09-26 14:24 UTC, justinehell approved these changes

2023-09-26 14:25 UTC, aboubakar14 approved these changes

2023-09-26 14:26 UTC, merged